### PR TITLE
Feature/time adjust secs

### PR DESCRIPTION
**Pull request by sipke**
As some test systems, like robot framework use local time, allow for timestamps to be adjusted for both output parser and robot listener.
For output parser provide a --time-adjust-secs option, which will adjust the timestamps from xml files by the given seconds (plus or negative). This will allow the user to archive data to database in utc time.
For the robot listener, allow the user to specify they want to adjust the time by system timezone and/or daylight savings offset.

There is a pull request against robotframework to allow saving utc timestamps, but even with that, older versions of robot framework would benefit from allow TestArchiver to adjust the time as desired.

### CODE REVIEW

**Review by Muusssi — CHANGES_REQUESTED** [review]
I had to think about this solution and in the end, I like the simplicity. I have been thinking the best approach to implement this type of functionality. 

Just couple of adjustments and things to consider before this can be released.

A) Our process is that new features are made against the develop branch and master is only moved for releases. So please change the target branch to develop. In my opinion this can be merged now to develop and further improvements listed here can be made in as separate changes before actual release.

B) This feature is probably somewhat difficult to understand by the users so more documentation is definitely needed. before releasing. A concrete usage example with context is definitely needed.

C) Using this feature should leave some  trace that the time stamps were adjusted for the test run. I am not yet sure what would the best approach for that. Possibly the best could be to add the information to the test run table but that would require a schema change. It could also simply be added as suite metadata which would be easily shown to the users in Epimetheus for example and would not require a schema change.

D) (More of an improvement idea) To allow even more versatile usage (especially considering existing archives), I would use two offsets: 
1. adjust using system time to UTC (as with the Listener option) 
2. additionally add the given time adjust seconds
This would easily allow correcting the timestamps to from any timezone to the archives timezone even if the archive database is not in UTC time

Thanks for a great contribution!

**Comment by sipke** [comment]
A) No problem, will do.
B) Pointers to where documentation should go will make sure I get it right and enough of it.
C) Because this was an option, I did not think leaving a trace would be needed, but can understand it useful, so will look into it. Metadata sounds promising.
D) I will add it. I assume you mean that D.1  is an additional option (e.g. --time-adjust-with-system-timezone), and D.2 is what is there already, and both can be used individually/independently and/or together.

**Comment by Muusssi** [comment]
B) This is a type of feature that I would mention in the README.md. Readme could be the place for the example and context explanation. All new features to be added to the next release can be listed to the top of release notes in the end of README.md so the new options could be listed there. More elaborate explanation for the cli options is also good.

C) The trace is useful for explaining that the timestamps have been "tampered with" especially when debugging if those adjustments went somehow wrong. I think the values of those two options should be added to the metadata object of the configuration (if they differ from zero). That should add the metadata to the top level suite.

D) Yes I mean D.1 as additional option and D.2 as it is but so that they can be used both separately or together. --time-adjust-with-system-timezone would always adjust to UTC with current system which is the easiest option and --time-adjust-secs should be an additional offset on top of that. This way you can use either of them or first with --time-adjust-with-system-timezone to set the time to UTC where ever the test are run and on top use the --time-adjust-secs to adjust the results to the time of the database (if it is not in UTC time).

**Comment by sipke** [comment]
Added commits to address changes discussed and updated target branch to develop.
Start with the README.md changes (there were two commits) I guess.

**Review by Muusssi — APPROVED** [review]

**Pull request merged**
